version: "3.8"

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: capitalpay-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: capitalpayadmin123
      MONGO_INITDB_DATABASE: capitalpay
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - capitalpay-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/capitalpay --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build:
      context: ./capitalpay-backend
      dockerfile: Dockerfile
    container_name: capitalpay-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:capitalpayadmin123@mongodb:27017/capitalpay?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-2024
      JWT_EXPIRE: 7d
      ADMIN_EMAIL: admin@capitalpay.com
      ADMIN_PASSWORD: admin123
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - backend_uploads:/app/uploads
    networks:
      - capitalpay-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend React App
  frontend:
    build:
      context: ./capitalpay-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000/api
    container_name: capitalpay-frontend
    restart: unless-stopped
    ports:
      - "3000:5173"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - capitalpay-network
    volumes:
      - ./capitalpay-frontend/src:/app/src
      - ./capitalpay-frontend/public:/app/public
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5173/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  capitalpay-network:
    driver: bridge
